In [8]:
a = torch.randn(2, 3)
b = torch.randn(1, 4)

In [9]:
a

tensor([[ 0.6406,  0.6722, -0.6013],
        [-0.6277,  2.7127,  1.9159]])

In [10]:
b

tensor([[-1.1906,  0.8922, -0.5574, -0.3694]])

In [12]:
c = torch.einsum('ij, kl->ikjl', a, b)
c

tensor([[[[-0.7627,  0.5716, -0.3571, -0.2367],
          [-0.8003,  0.5997, -0.3747, -0.2483],
          [ 0.7159, -0.5365,  0.3352,  0.2221]]],


        [[[ 0.7474, -0.5601,  0.3499,  0.2319],
          [-3.2299,  2.4203, -1.5122, -1.0022],
          [-2.2811,  1.7094, -1.0680, -0.7078]]]])

In [14]:
c.reshape(2, 12)

tensor([[-0.7627,  0.5716, -0.3571, -0.2367, -0.8003,  0.5997, -0.3747, -0.2483,
          0.7159, -0.5365,  0.3352,  0.2221],
        [ 0.7474, -0.5601,  0.3499,  0.2319, -3.2299,  2.4203, -1.5122, -1.0022,
         -2.2811,  1.7094, -1.0680, -0.7078]])

In [15]:
import numpy as np
res = np.kron(a.numpy(), b.numpy()) 
res

array([[-0.7627399 ,  0.57156706, -0.35710365, -0.23666897, -0.80032015,
         0.5997282 , -0.3746982 , -0.24832967,  0.7159272 , -0.53648746,
         0.33518663,  0.22214356],
       [ 0.74739164, -0.5600657 ,  0.34991786,  0.23190661, -3.2298667 ,
         2.420334  , -1.5121764 , -1.0021887 , -2.2811198 ,  1.7093809 ,
        -1.067987  , -0.70780396]], dtype=float32)